export const OPEN_DATABASE_DIRECTORY = "REQUEST_CONNECTION_HISTORY";
export const OPEN_CONNECTION = "REQUEST_CONNECTION_HISTORY";
export const REQUEST_CONNECTION_HISTORY = "REQUEST_CONNECTION_HISTORY";
export const RECEIVE_CONNECTION_HISTORY = "RECEIVE_CONNECTION_HISTORY";